# Generated by Django 3.1.6 on 2021-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='MANUFACTURER')),
                ('series', models.CharField(max_length=20, verbose_name='SERIES')),
                ('generation', models.CharField(max_length=20, verbose_name='GENERATION')),
            ],
        ),
        migrations.CreateModel(
            name='Maker_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_list', models.CharField(max_length=50, verbose_name='MAKER_LIST')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('cpu', models.CharField(max_length=50, verbose_name='CPU')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
                ('gpu', models.CharField(max_length=50, verbose_name='GPU')),
                ('battery', models.CharField(max_length=20, verbose_name='BATTERY')),
                ('volume', models.CharField(max_length=20, verbose_name='VOLUME')),
                ('weight', models.CharField(max_length=20, verbose_name='WEIGHT')),
                ('display', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='DISPLAY')),
                ('maker', models.CharField(max_length=50, verbose_name='MAKER')),
                ('sw_os', models.CharField(default='', max_length=20, verbose_name='SW_OS')),
                ('price', models.CharField(max_length=50, verbose_name='PRICE')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='IMAGE')),
                ('content', models.ImageField(blank=True, upload_to='', verbose_name='CONTENT')),
            ],
        ),
        migrations.CreateModel(
            name='Ram_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_weight', models.CharField(max_length=50, verbose_name='RAM_WEIGHT')),
            ],
        ),
    ]
