# Generated by Django 3.1.6 on 2021-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('cpu', models.CharField(max_length=50, verbose_name='CPU')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('gpu', models.CharField(max_length=50, verbose_name='GPU')),
                ('battery', models.IntegerField(verbose_name='BATTERY')),
                ('volume', models.IntegerField(verbose_name='VOLUME')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='WEIGHT')),
                ('display', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='DISPLAY')),
                ('maker', models.CharField(max_length=50, verbose_name='MAKER')),
                ('sw_os', models.CharField(default='', max_length=20, verbose_name='SW_OS')),
                ('price', models.IntegerField(verbose_name='PRICE')),
                ('image', models.ImageField(blank=True, upload_to='product/', verbose_name='IMAGE')),
                ('content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
    ]
