# Generated by Django 3.1.6 on 2021-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(max_length=50, verbose_name='BATTERY'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=50, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(max_length=50, verbose_name='VOLUME'),
        ),
    ]
