# Generated by Django 3.1.6 on 2021-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu_list',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='cpu_list',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='cpu_list',
            name='series',
        ),
        migrations.RemoveField(
            model_name='ram_list',
            name='ram_weight',
        ),
        migrations.AddField(
            model_name='cpu_list',
            name='cpu_list',
            field=models.CharField(default='', max_length=50, verbose_name='CPU_LIST'),
        ),
        migrations.AddField(
            model_name='ram_list',
            name='ram_volume',
            field=models.CharField(default='', max_length=20, verbose_name='RAM_VOLUME'),
        ),
    ]
