# Generated by Django 3.1.6 on 2021-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210202_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_list', models.CharField(max_length=50, verbose_name='MAKER_LIST')),
            ],
        ),
    ]
