# Generated by Django 3.1.6 on 2021-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_list', models.IntegerField(default='', verbose_name='DISPLAY_LIST')),
            ],
        ),
        migrations.CreateModel(
            name='Gpu_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_list', models.CharField(default='', max_length=50, verbose_name='GPU_LIST')),
            ],
        ),
        migrations.CreateModel(
            name='Os_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_list', models.CharField(default='', max_length=20, verbose_name='OS_LIST')),
            ],
        ),
        migrations.CreateModel(
            name='Ssd_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssd_volume', models.CharField(default='', max_length=20, verbose_name='SSD_VOLUME')),
            ],
        ),
        migrations.CreateModel(
            name='Weight_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_list', models.IntegerField(default='', verbose_name='WEIGHT_LIST')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='PRICE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='WEIGHT'),
        ),
    ]
